const ffmpeg = [
  {
    type: 'category',
    label: 'FFmpeg',
    link: { type: 'doc', id: 'ffmpeg/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'ffmpeg',
      },
    ],
  },
]

const git = [
  {
    type: 'category',
    label: 'Git',
    link: { type: 'doc', id: 'git/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'git',
      },
    ],
  },
]

const docker = [
  {
    type: 'category',
    label: 'Docker',
    link: { type: 'doc', id: 'docker/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'docker',
      },
    ],
  },
]

const network = [
  {
    type: 'category',
    label: 'Network',
    link: { type: 'doc', id: 'network/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'network',
      },
    ],
  },
]


module.exports = {
  ffmpeg,
  git,
  docker,
  network,
}
