const docs = [
  {
    type: 'category',
    label: 'FFmpeg',
    link: { type: 'doc', id: 'docs/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'docs',
      },
    ],
  },
]

const blog = [
  {
    type: 'category',
    label: 'Git',
    link: { type: 'doc', id: 'blog/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'blog',
      },
    ],
  },
]


module.exports = {
  docs,
  blog,
}
